# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'lab5.ui'
# Created by: PyQt5 UI code generator 5.15.7
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(446, 345)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PWMgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.PWMgroupBox.setGeometry(QtCore.QRect(40, 20, 361, 121))
        self.PWMgroupBox.setObjectName("PWMgroupBox")
        self.rb_0 = QtWidgets.QRadioButton(self.PWMgroupBox)
        self.rb_0.setGeometry(QtCore.QRect(20, 60, 51, 23))
        self.rb_0.setObjectName("rb_0")
        self.rb_45 = QtWidgets.QRadioButton(self.PWMgroupBox)
        self.rb_45.setGeometry(QtCore.QRect(90, 60, 51, 23))
        self.rb_45.setObjectName("rb_45")
        self.rb_90 = QtWidgets.QRadioButton(self.PWMgroupBox)
        self.rb_90.setGeometry(QtCore.QRect(160, 60, 51, 23))
        self.rb_90.setObjectName("rb_90")
        self.rb_135 = QtWidgets.QRadioButton(self.PWMgroupBox)
        self.rb_135.setGeometry(QtCore.QRect(230, 60, 51, 23))
        self.rb_135.setObjectName("rb_135")
        self.rb_180 = QtWidgets.QRadioButton(self.PWMgroupBox)
        self.rb_180.setGeometry(QtCore.QRect(300, 60, 51, 23))
        self.rb_180.setObjectName("rb_180")
        self.PWMslider = QtWidgets.QSlider(self.centralwidget)
        self.PWMslider.setGeometry(QtCore.QRect(30, 170, 381, 41))
        self.PWMslider.setOrientation(QtCore.Qt.Horizontal)
        self.PWMslider.setObjectName("PWMslider")
        self.Releasebutton = QtWidgets.QPushButton(self.centralwidget)
        self.Releasebutton.setGeometry(QtCore.QRect(40, 230, 131, 51))
        self.Releasebutton.setObjectName("Releasebutton")
        self.SignalText = QtWidgets.QLabel(self.centralwidget)
        self.SignalText.setGeometry(QtCore.QRect(200, 230, 201, 51))
        self.SignalText.setText("")
        self.SignalText.setObjectName("SignalText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 446, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PWMgroupBox.setTitle(_translate("MainWindow", "PWM"))
        self.rb_0.setText(_translate("MainWindow", "0"))
        self.rb_45.setText(_translate("MainWindow", "45"))
        self.rb_90.setText(_translate("MainWindow", "90"))
        self.rb_135.setText(_translate("MainWindow", "135"))
        self.rb_180.setText(_translate("MainWindow", "180"))
        self.Releasebutton.setText(_translate("MainWindow", "Release Motor"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())